### ISSUE TITLE
Tag a v6.1.2 release for resolving Composer conflict

### ISSUE THREAD

**Issue by Minishlink** [Spomky-Labs/jose#150]
Hi,

Could you please tag a new minor release? Your last commit fixes a Composer conflict.

**Comment by Spomky** [comment]
Hi,

I have other modification to perform before adding a new tag:

- Fix #149.
- Merge the https://github.com/Spomky-Labs/php-aes-gcm/pull/4 and modify this library accordingly.

Anyway I am not sure the minor change in the 923b6e904994c23ce553ae2c01fcee09bc419839 will fix the issue you referenced.
From my POV, you should modify the `composer.json` file of https://github.com/web-push-libs/web-push-php as follows:

```yaml
{
  ...
  "require": {
    "php": "^5.6|^7.0",
    "kriswallsmith/buzz": ">=0.6",
    "spomky-labs/jose": "^6.0"
  },
  "require-dev": {
    "phpunit/phpunit": "^4.8|^5.0"
  },
  ....
}
```

I think I will submit a PR on that web push library, I noted that some improvements could be done.
Feel free to contact me on [Gitter](https://gitter.im/Spomky-Labs/jose?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) to discuss about that topic.
